# Generated by Django 6.0.4 on 2026-04-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=250)),
                ('assignee', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='M', max_length=1)),
                ('time_unit', models.CharField(choices=[('H', 'Hour'), ('D', 'Day'), ('W', 'Week')], default='H', max_length=1)),
                ('estimate_time_to_complete', models.FloatField(null=True)),
                ('reported_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('T', 'Todo'), ('I', 'In Progress'), ('O', 'On Hold'), ('D', 'Done')], default='T', max_length=1)),
                ('hold_on_reason', models.CharField(max_length=100)),
                ('completed_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
