# Generated by Django 6.0.4 on 2026-04-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hold_on_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
